#!/usr/bin/env python3
"""Substep 1.1 — corpus survey.

Inventories every entry under `Stories written with Narracode/*/versions/`.
Classifies the NAME's provenance signal only. Does not determine provenance;
that is substep 1.2 and requires jhave.

Outputs corpus/survey.json and corpus/survey.md
"""
import os, re, json, sys
from collections import defaultdict

ROOT = "Stories written with Narracode"
OUT = "corpus"

# Agent markers only. A stylistic-operation name ("draft", "revision",
# "rewrite", "densified") says WHAT was done, not WHO did it -> ambiguous.
AGENT_HUMAN = re.compile(r'\b(human|jhave|user|hand)\b', re.I)
AGENT_MACHINE = re.compile(r'\b(automode|auto-run|autorun|initiator|tell-scan)\b', re.I)
ADJACENT = re.compile(r'(^|[-_])(pre|before|post|after)[-_]', re.I)

VERNUM = re.compile(r'^v(\d+)')
DATE = re.compile(r'(\d{4}-\d{2}-\d{2})')


def classify_name(name):
    if ADJACENT.search(name):
        return "ambiguous-temporal"
    if AGENT_HUMAN.search(name):
        return "explicit-human"
    if AGENT_MACHINE.search(name):
        return "explicit-machine"
    if re.search(r'[a-z]', name):
        return "content-only"
    return "none"


def words(path):
    try:
        return len(open(path, encoding="utf-8", errors="replace").read().split())
    except Exception:
        return 0


def survey():
    records, exceptions = [], []
    for story in sorted(os.listdir(ROOT)):
        vdir = os.path.join(ROOT, story, "versions")
        if not os.path.isdir(vdir):
            continue
        for entry in sorted(os.listdir(vdir)):
            p = os.path.join(vdir, entry)
            rec = {"story": story, "entry": entry, "path": p}
            m, d = VERNUM.match(entry), DATE.search(entry)
            rec["vnum"] = int(m.group(1)) if m else None
            rec["date"] = d.group(1) if d else None
            rec["name_signal"] = classify_name(entry)

            if os.path.islink(p):
                rec["type"] = "other"; exceptions.append((story, entry, "symlink"))
            elif not os.path.isdir(p):
                rec["type"] = "loose-file"; exceptions.append((story, entry, "not a directory"))
            else:
                ddir = os.path.join(p, "drafts")
                if not os.path.isdir(ddir):
                    rec["type"] = "metadata-only"
                    exceptions.append((story, entry, "no drafts/ subdirectory"))
                else:
                    md = sorted(f for f in os.listdir(ddir) if f.endswith(".md"))
                    if not md:
                        rec["type"] = "metadata-only"
                        exceptions.append((story, entry, "drafts/ present but empty"))
                    else:
                        rec["type"] = "snapshot"
                        rec["drafts"] = md
                        rec["draft_words"] = {f: words(os.path.join(ddir, f)) for f in md}
                        rec["words"] = sum(rec["draft_words"].values())
                        rec["has_poetics"] = os.path.exists(os.path.join(p, "POETICS.md"))
            records.append(rec)
    return records, exceptions


def continuity(records):
    """For each story, consecutive snapshot pairs and their shared drafts."""
    by_story = defaultdict(list)
    for r in records:
        if r["type"] == "snapshot":
            by_story[r["story"]].append(r)
    out = []
    for story, snaps in by_story.items():
        snaps.sort(key=lambda r: (r["date"] or "", r["vnum"] if r["vnum"] is not None else 999))
        for a, b in zip(snaps, snaps[1:]):
            sa, sb = set(a["drafts"]), set(b["drafts"])
            out.append({"story": story, "from": a["entry"], "to": b["entry"],
                        "shared": sorted(sa & sb),
                        "only_from": sorted(sa - sb), "only_to": sorted(sb - sa)})
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    records, exceptions = survey()
    trans = continuity(records)
    json.dump({"records": records, "transitions": trans,
               "exceptions": [{"story": s, "entry": e, "reason": r} for s, e, r in exceptions]},
              open(f"{OUT}/survey.json", "w"), indent=1)

    counts = defaultdict(int)
    for r in records:
        counts[r["type"]] += 1
    sig = defaultdict(int)
    for r in records:
        if r["type"] == "snapshot":
            sig[r["name_signal"]] += 1

    L = ["# Corpus survey — substep 1.1", "",
         f"Generated by `tools/survey_corpus.py`. Entries: **{len(records)}**.", "",
         "## Entry types", "", "| type | count |", "|---|---|"]
    for k in sorted(counts):
        L.append(f"| {k} | {counts[k]} |")
    L += ["", "## Name signal, snapshots only", "",
          "Classification of the **name**, not a determination of provenance.", "",
          "| signal | count | auto-labellable |", "|---|---|---|"]
    auto = {"explicit-human": "yes", "explicit-machine": "yes"}
    for k in sorted(sig):
        L.append(f"| {k} | {sig[k]} | {auto.get(k,'**no — needs jhave**')} |")

    need = [r for r in records if r["type"] == "snapshot"
            and r["name_signal"] in ("content-only", "ambiguous-temporal", "none")]
    L += ["", f"**Snapshots requiring a jhave decision: {len(need)}**", "",
          "## Ambiguous — needs jhave", "",
          "| story | snapshot | signal | drafts | words |", "|---|---|---|---|---|"]
    for r in sorted(need, key=lambda r: (r["story"], r["date"] or "", r["vnum"] or 0)):
        L.append(f"| {r['story']} | `{r['entry']}` | {r['name_signal']} | "
                 f"{len(r['drafts'])} | {r['words']:,} |")

    L += ["", "## Exceptions", "", "| story | entry | reason |", "|---|---|---|"]
    for s, e, r in exceptions:
        L.append(f"| {s} | `{e}` | {r} |")

    L += ["", "## Assumptions made", "",
          "- Snapshots live only in `<story>/versions/<snapshot>/drafts/*.md`.",
          "- A directory without `drafts/` cannot yield a pair and is excluded.",
          "- Chronological order is (date-in-name, version-number); `v10` sorts after `v9`.",
          "- Drafts are matched across snapshots by exact filename; no fuzzy matching.",
          "- `pre-`/`before-`/`post-`/`after-` describe an adjacent state, so the name",
          "  cannot settle this snapshot's own provenance.",
          "- Stylistic-operation names (`draft`, `revision`, `rewrite`, `densified`,",
          "  `refinement`) name what was done, not who did it, so they are NOT auto-labelled."]
    open(f"{OUT}/survey.md", "w").write("\n".join(L) + "\n")

    print(f"entries {len(records)}  " + "  ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    print(f"transitions {len(trans)}   need-jhave {len(need)}")


if __name__ == "__main__":
    sys.exit(main())
